object Constants {
    const val REPORT_FIREBASE_CRASHLYTICS = "REPORT_FIREBASE_CRASHLYTICS"
    const val REPORT_FIREBASE_ANALYTICS = "REPORT_FIREBASE_ANALYTICS"
    const val REPORT_INSTABUG = "REPORT_INSTABUG"

    const val BASE_URL_ID_API = "BASE_URL_ID_API"
    const val BASE_URL_PROXY_API = "BASE_URL_PROXY_API"

    const val INSTABUG_API_TOKEN = "INSTABUG_API_TOKEN"
}
